### ISSUE TITLE
Rxbus + Sticky Events?

### ISSUE THREAD

**Issue by sirvon** [kaushikgopal/Android-RxJava#10]
What about making the events sticky?

If I use rxbus with android's sharing mechnism how will I get the event in the activity where
the shared info is received.

The event will be sent before the activity is opened...do I have to persist the event? 
would'nt that make a bus irrelevant?

**Comment by kaushikgopal** [comment]
Sticky events can be achieved by way of using a different `Subject` in your RxBus implementation. For e.g. use a [`BehaviorSubject`](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/behaviorsubject.md)

**Comment by ursusursus** [comment]
That would make only the last event posted sticky regardless of event type. In eventBus it used to be sticky per evenType .. how would I handle that? Hashmap of eventType, PublishSubject? Feels wrong..

**Comment by kaushikgopal** [comment]
@ursusursus  - honestly, I would find a way to workaround needing to use an event bus at that point altogether. The Hashmap would work, but dang that would be pretty heavy handed. I would definitely explore finding alternative ways of handling that usecase at that point.
