### ISSUE TITLE
getRxBusSingleton();

### ISSUE THREAD

**Issue by sirvon** [kaushikgopal/Android-RxJava#8]
Your calling 

```java
_rxBus = ((MainActivity) getActivity()).getRxBusSingleton();
```

but I dont see this method in RxBus.java??

edit:
---------
I see it's in the host activity. But why isn't it in the RxBus class?

Can you explain the getsingleton call and science behind it?

thanks!

**Comment by kaushikgopal** [comment]
it doesn't have anything to do with RxJava or the RxBus specifically. `Singleton` is a pattern of development where you assure a single global object throughout the system. So if i access the singleton object (RxBus in this case) anywhere else via that method, I'm assured of getting the exact same instance.
